# Generated by Django 2.2.1 on 2019-06-28 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='phono',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
